name: doc
on:
  pull_request:
    branches:
      - master
    paths:
      - 'docs/**'
      - '.github/workflows/doc.yml'
  push:
    branches:
      - master
    paths:
      - 'docs/**'
      - '.github/workflows/doc.yml'
  workflow_dispatch: # useful for testing tx pushes


defaults:
  run:
    working-directory: docs

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python requirements
        run: |
          pip install -r requirements.txt
          
      - name: Build documentation
        run: mkdocs build

      - uses: actions/upload-artifact@v4
        if: ${{ github.event_name == 'pull_request' }}
        with:
          name: docs
          path: docs/site
          if-no-files-found: error

      - name: Deploy to GitHub Pages
        if: contains(fromJSON('["push", "workflow_dispatch"]'), github.event_name)
        run: mkdocs gh-deploy --force
